### ISSUE TITLE
Real-time page color update issue

### ISSUE THREAD

**Issue by Shen-Ming-Hong** [whitphx/streamlit-theme-editor#1]
## Description
I am experiencing an issue where the page color does not update in real-time when using the Streamlit Theme Editor. 

## Steps to Reproduce
1. Clone the repository: `git clone https://github.com/whitphx/streamlit-theme-editor.git`
2. Run the application: `streamlit run app.py`
3. Change the color theme using the editor.

## Expected Behavior
When the "Apply theme to this page" checkbox is checked, the page color should update in real-time as the changes are made in the theme editor.

## Actual Behavior
After checking the "Apply theme to this page" checkbox, the page color does not update in real-time regardless of which color section is adjusted. It seems that `st.rerun` is called correctly, but the color changes are not reflected.

## Environment
- OS: Windows 11
- Browser: Microsoft Edge
- Streamlit Version: 1.36.0
- Python Version: 3.11.4

**Comment by whitphx** [comment]
Thank you for the report.
Unfortunately I couldn't reproduce the problem in my env where the Python ver. is different though.
Let me keep this issue open but gather more info.

My env:
* OS: Windows 11 / macOS 14
* Browser: Microsoft Edge / Google Chrome
* Streamlit Version: 1.36.0
* Python version: 3.12.4

Also can you try other settings like using Chrome?
Thanks.
